// Generated by https://quicktype.io

export interface Transaction {
  uuid: string;
  outlet_id: number;
  outlet_name: string;
  voucher_id: number;
  trx_id: string;
  shipper_order_id: string;
  sum_item: number;
  order_type_id: number;
  order_type_name: string;
  order_manual: number;
  order_status: number;
  order_status_text: string;
  total_price: number;
  total_basic_price: number;
  final_price: string ;
  qris_code: number;
  alias_name: string;
  description_text: string;
  status_paid: number;
  status_paid_name: string;
  discount: number;
  total_ppn: number;
  total_changes: number;
  customer_uuid: string;
  customer_id: string;
  customer_name: string;
  online_customer_id: string;
  online_customer_uuid: string;
  online_customer_name: string;
  online_customer_phone: string;
  online_customer_email: string;
  invoice_number: string;
  digital_payment_uuid: string;
  digital_payment_name: string;
  user_id: number;
  username: string;
  split_product: number;
  split_bill: number;
  payment_method: number;
  payment_method_text: string;
  method_payment: string;
  method_payment_name: string;
  method_payment_image: string;
  delivery_method: number;
  total_payment: number;
  note: string;
  queue_order: string;
  day_cash_receipt: number;
  is_notif_cash_receipt: boolean;
  is_online_order: number;
  parent_trx_id: string;
  paid_at: number;
  is_kasbon: number;
  updated_unix_time: number;
  unix_time: number;
  due_time: string;
  due_date: string;
  created_at: string;
  items: TransactionItem[];
}

export interface TransactionItem {
  count: number;
  extra_price_variant: number;
  image: string;
  is_print_struct: number;
  name: string;
  note: string;
  ppn: number;
  price: number;
  product_uuid: string;
  type_ppn: number;
  variant?: Variant[];
}

export interface Variant {
  items: VariantItem[];
  name: string;
  uuid: string;
}

export interface VariantItem {
  extra_price: number;
  name: string;
  uuid: string;
}
